### ISSUE TITLE
Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by toothrot** [hpcloud/hipchat-notification-resource#14]
When trying to do a simple put, I receive the following error:

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/scripts/hipChatClient.js:15:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

configuration:
```yaml
jobs:
  - name: partyparrot
    plan:
      - put: hipchat-notification
        params:
          color: green
          from: "Concourse CI"
          message:
            template: "(partyparrot)"
resources:
  - name: hipchat-notification
    type: hipchat-notification-resource
    source:
      hipchat_server_url: https://api.hipchat.com
      token: [redacted]
      room_id: [redacted]

resource_types:
  - name: hipchat-notification-resource
    type: docker-image
    source:
      repository: toothrot/hipchat-notification-resource
```
